<?php
session_start();
$nev=$_SESSION["user"]["username"];
?>

<!DOCTYPE html>
<html lang="hu">
<head>
    <link href="css/dizajn.css" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <title>Avatár</title>
    <link href='https://fonts.googleapis.com/css?family=Jua' rel='stylesheet'>
    <link rel="icon" href="képek/logok/avatar_icon.png"/>
</head>
<body>

<nav class="flex-container" >
    <ul>
       <li> <a id="fooldalgomb" href="Fooldal.php">
            <img id="lotus" src="képek/logok/lotus.png" alt="Főoldal logó" >
        </a>
        <li>
        <li><a href="Karakterek.php" class="link">Karakterek</a></li>
        <li><a href="Aang_legendaja.php" class="link">Aang legendája</a></li>
        <li><a href="Korra_legendaja.php" class="link">Korra legendája</a></li>
        <li><a href="Vilaga.php" class="link">Világa</a></li>
        <li><a href="Artwork.php" class="link">Artwork</a></li>
    </ul>
        <?php if(isset($_SESSION["user"]) && $nev==="admin"){ ?>
            <a id="bejelentkezes" href="Admin.php" >Profil</a>
        <?php } else if (isset($_SESSION["user"])) { ?>
            <a id="bejelentkezes" href="Profil.php" >Profil</a>
        <?php } else { ?>
            <a id="bejelentkezes" href="Bejelentkezes.php">Bejelenkezes</a>
        <?php } ?>
</nav>
<div id="container">
    <video controls autoplay >
        <source src="videok/Avatar-%20The%20Legend%20Of%20Korra%20Trailer%20(OFFICIAL).mp4" type="video/mp4">
    </video>
    <header>Avatár Korra legendája sorozat leírása</header>
    <h2 class="alcim" id="Elso">1. Évad: Levegő</h2>
        <section  class="karakteroldal">
            <p > <img src="képek/Korra/k1.png" class="kepek" alt="Korra 1 évad"> </p>
    <p>Korra a kamaszok forrófejűségével veti bele magát az életbe. Nem bírja megvárni, hogy Tenzin először rendezze a dolgokat Köztársaságvárosban, elhatározza, hogy megszökik a Déli-sarkról. Hajóra száll jegesmedvekutyájával, Nagával együtt. Megérkezésük után percekkel máris galibába keverednek: mikor útbaigazítást kér egy bolti eladótól, megjelenik egy bűnbanda, hogy védelmi pénzt szedjen be a boltostól. Korra ezt nem hagyja, és jól eltángálja a bűnözőket, akik a Tripla Terror tagjai (nevük utalás a négy elem közül háromra: víz, tűz, föld). Egy rendőrjárőr észreveszi az eseményeket, és a bandán kívül Korrát is le akarják tartóztatni önbíráskodásért. Korra ellenáll a letartóztatásnak, és megpróbál elmenekülni, de elfogják. A kapitányságon nem más hallgatja ki a lányt, mint a város rendőrfőnöke, Lin Beifong, aki szigorú, hajlíthatatlan személyiség. Befut Tenzin is, aki már értesült a történtekről és kéri a rendőrkapitányt, hogy engedje szabadon Korrát, majd Tenzin, mint tanácsos vállalja a felelősséget mindenért. Lin Beifong beleegyezik, azzal a feltétellel, hogy a lányt azonnal hazaküldik a Déli-sarkra. A kikötőben Tenzin átgondolja a dolgot, és végül marasztalja Korrát, aminek a lány nagyon örül. A tanácsnok azzal indokolja a döntést, hogy igazából Korra testesíti meg Aang Avatar örökségét, és nem az Egyesült Köztársaság. Beleegyezik abba, hogy azonnal megkezdje Korra tanítását, hogy a levegő elemét is magáénak mondhassa.

        Korra tehát Tenzin tanítványa lesz. Mivel soha nem gyakorolt semmiféle spirituális folyamatot, ezért a meditációs gyakorlatok untatják őt, az egyszerű lelkületű, ugyanakkor forrófejű lányt. Nehéz belátnia, hogy a levegőidomítás összefügg a lelki, nem anyagias élettel, hiszen a Levegő Nomádjai mindig is a világi vágyakról való lemondást gyakorolták, hogy belső békére és megvilágosodásra tegyenek szert. Tenzint is túl szigorúnak találja, mint tanárt. Lopva hallgatja a Fehér Lótusz katonáinak rádióját, akik állandóan az Idomáraréna mérkőzésein lógnak, és erős sóvárgás támad benne azért, hogy láthasson egyszer élőben is egy ilyen meccset. Tenzin rajtakapja a rádióhallgatáson és figyelmezteti a lányt, hogy ne foglalkozzon ilyen sületlenséggel, de Korra természetesen nem fogad szót és egy este átszökik a Légtemplom-szigetről a városba, egyenesen az arénába. Összeismerkedik Makóval és Bolinnal, a két testvérrel, akik a Tűzmenyétek nevű csapatot alkotják. Mako tűzidomár, Bolin pedig földidomár. Éppen egy mérkőzés előtt vannak, aztán belépnek a küzdőtérre és legyőzik a másik csapatot. Korra teljesen felizgul attól, amit látott, és bemutatja, hogyan bánik a föld elemmel. Mako, az idősebb testvér nem könnyen barátkozik és nehéz őt elkápráztatni, ám Bolin érzi, hogy Korra nagyon tehetséges. Következő alkalommal, amikor ismét meglóg az arénába, látja, hogy a testvérek csüggedten ülnek az öltözőben, mert a vízidomárjuk, Hasook lelépett, emiatt vesztettek. Korra rögtön felajánlja, hogy beáll vízidomárnak. Mako nem akar beleegyezni, de mire föleszmél, a lány a porondon van. A meccset szokás szerint a rádió is közvetíti, és Tenzin meghallja, hogy a kommentátor éppen felfedezi, hogy a Tűzmenyéteknél új vízidomár van, az Avatar személyében. Dühös lesz és az arénába megy, ahol számon kéri Korrát, aki ellenszegül mesterének. A küzdelem folytatódik, és Korra arra gondol, hátha megfordíthatja a kieséssel fenyegető helyzetet: alkalmazni kezdi Tenzin egyik módszerét, és ennek segítségével kiüti ellenfeleit. Tenzin is végignézi a befejezést, és elégedetten távozik. A meccs után meg is mondja Korrának, hogy az aréna mégis segíthet neki, és nem fogja ezentúl tiltani, hogy odamenjen. Mako is megenyhül és fölenged Korra sikere nyomán, és hozzájárul ahhoz, hogy a csapatban maradjon.

        A Tűzmenyétek anyagi helyzete egyre nehezebb, és soha nem is volt fényes. Pénzt kellene felhajtaniuk, ha nem akarják, hogy kizárják őket a versenyzésből. Mako elmegy dolgozni a város erőművébe, Bolin pedig az idomított tűzmenyétjével, Pabuval az utcán próbál mutatványokkal pénzt keresni, de őt elcsábítja a Tripla Terror egy jelentős összeggel, mert kellenek a verőemberek, ugyanis bandaháború készül Köztársaságvárosban. Ráadásul régebben a testvérpár kapcsolatban állt a Tripla Terrorral. Mako az öccsét keresi, magával viszi Korrát is, és kinyomozzák az igazságot. A bűnszervezet főhadiszállásán azonban chi-blokkolókba ütköznek, akik előtte megtámadták a bandatagokat és most el akarják őket hurcolni. Harcképtelenné teszik Makót és Korrát, így egérutat nyernek, magukkal hurcolva Bolint és néhány bűnözőt. Korráék szereznek néhány egyenlőségi szórólapot, amelyek egy rendezvényt reklámoznak, a hátoldalak pedig összerakva egy térképet adnak. Ennek nyomán megtalálják a rendezvény helyszínét, ahol óriási tömeg verődik össze. Amon, az egyenlőségiek vezére gyújtó hatású beszédet mond, elmesélve azt, hogy nem-idomár családból származik és a szüleit egy tűzidomár ölte meg. A világon minden rosszat az idomításnak tulajdonít, és elmondása szerint a szellemek adtak neki erőt ahhoz, hogy elvehesse bármelyik idomár erejét egy életre, hogy ezáltal igazi egyensúlyt hozzon a világra. A beszéd után láthatóvá válnak az elhurcolt Tripla Terror-tagok, köztük Bolin is. Amon megfosztja az erejétől Villámcsapta Zoltot, a tűzidomár bandavezért, Sötét Shint, egy vízidomárt és egy földidomárt is, és éppen Bolinon a sor, amikor Korra és Mako trükkel megmenti őt. A chi-blokkolók üldözőbe veszik őket majd Amon alvezére, a hadnagy áramütéssel kifekteti a testvéreket, de jön Korra és így el tudnak menekülni. Korrát sokkolja az, amit a rendezvényen látott, Tenzin is alig képes elhinni, miután a lány beszél róla neki.

        Korrát rémálmok kínozzák, melyekben a chi-blokkolók elfogják, majd Amon elé hurcolják őt, aki elveszi az erejét. Nagyon fél egy esetleges összecsapástól, ezért elutasítja Tarrlok, a városi tanácstag felkérését, hogy álljon be az újonnan szervezett speciális alakulatába, mely a forradalmárokkal venné fel a harcot. Tarrlok egyre gálánsabb és drágább ajándékokat küld Korrának, de ő mindig nemet mond, egészen addig, amíg a tanácsnok egy bált rendez a tiszteletére. Ezen a rendezvényen az Avatar az újságírók kérdéseitől elveszti a türelmét, és pillanatnyi felindultságában mégis bejelenti, hogy tagja lesz az akciócsoportnak. Első bevetése sikeres, ő is és Tarrlok is felbuzdul ezen, amikor letartóztatnak néhány chi-blokkolót. Eközben Makót megtalálja a szerelem egy gazdag lány személyében, aki nem más, mint Asami Sato, az autógyáros Hiroshi Sato gyermeke. Asami bemutatja a fiút apjának, aki felajánlja, hogy szponzorálni fogja a Tűzmenyéteket. Mako természetesen elfogadja az ajánlatot, hiszen így megmenekülnek a filléres gondoktól, részt vehetnek a bajnokságon. Korrától számon kérik az újságírók, hogy még mindig nem fogta el magát Amont, amin Korra újból feldühődik, és a sajtó képviselői előtt párbajra hívja ki a forradalmi vezetőt. A helyszín Aang Avatár emlékszigete, ahol Korra türelmetlenül vár, és mikor azt hiszi, hogy egyáltalán nem jön el Amon, a chi-blokkolók lecsapnak rá és hajszálra minden úgy történik, mint a rémálmaiban: Amon elé hurcolják a tehetetlen Avatart. Korra nagyon retteg, de Amon közli vele, hogy bár legszívesebben azonnal elvenné az erejét, ez még túl korai lenne, mivel az Avatart akarja sorra keríteni legutoljára. Ezután egy jól irányzott ütéssel elkábítja a lányt, akire órák múlva rátalál Tenzin. Korra sírva beszél neki a félelméről, hogy egész végig rettegett Amontól

        Az Avatar egyre többet edz Makóval és Bolinnal, és közben egyre jobban összecsiszolódnak emberileg is. Ez már csak azért is fontos, mert közeleg a bajnokság. Nem sokkal a nyolcaddöntő előtt Mako és Bolin Korráról beszélgetnek. Bolin arról érdeklődik, hogy bátyja szerint Korra jó lenne-e barátnőnek, amire Mako azt válaszolja, hogy Korra aranyos, kedves stb., de valamiért mégsem lenne jó ötlet járni vele, leginkább azért, mert ő csapattárs, és az ilyen kapcsolatok nem túl sikeresek. Igazi látnoki szavak ezek. A nyolcaddöntőt simán megnyerik a Tűzmenyétek, mindhárman fel vannak dobva. Korrának tetszik Mako, de őt lestoppolta Asami. Tenzin felesége, Pema elárulja Korrának, hogy neki sem volt könnyű dolga, amikor Tenzinért törte magát, de látta, hogy a férfi nem a megfelelő nővel van együtt, és ezt kihasználva egy napon őszintén megvallotta neki az érzéseit, így nyerte el őt végül. Korra ezen felbuzdulva szintén így tesz, de Mako elutasítja őt. Bolin eközben úgy gondolja, ha már Mako foglalt, akkor nyugodtan rástartolhat Korrára, aki elfogadja a közeledést, és jókat vannak együtt. De Mako próféciája egyszercsak beteljesül: az éppenhogy összejött negyeddöntő után elmondja Korrának, hogy igazából sem ő, sem Asami nem hagyja őt hidegen. Korra ekkor felidézi Pema példáját, és megcsókolja Makót, pont akkor, mikor Bolin közeleg, virágcsokorral a kezében. Az ifjú földidomár szíve összetörik, árulónak tartja a bátyját, Mako úgy szedi össze őt Narook tésztakifőzdéjéből, ahová zokogva elvonult. Rosszkor jött az egész, pont az elődöntő előtt. A csapat nagyon nehezen küzd a pályán, végül kizárólag Korrának köszönhető a győzelem, így a döntőbe jutnak, ahol is a Farkasdenevérek lesznek az ellenfelek, ők a címvédők immár három éve. Vezetőjük, a vízidomár Tahno, aki arrogáns és mindig sértegeti az ellenfeleit, már kipécézte magának az Avatart.

        A Tűzmenyétek edzés közben rádiót hallgatnak, amikor az adást Amon bejelentése szakítja meg, aki megfenyegeti a város tanácsát, követelve, hogy zárják be az arénát, mert ellenkező esetben a következmények súlyosak lesznek. A tanácsban a tagok egyetértenek ezzel, mivel nem akarják kockáztatni sem a versenyzők, sem a nézők biztonságát. A felháborodott Tűzmenyétek ellenben gyávasággal vádolják a tanácsot, és teljesen váratlan oldalról kapnak tüzérségi támogatást, mert Lin Beifong is csatlakozik hozzájuk. Ő megígéri a tanács előtt, hogy a rendőrség által fogja garantálni a biztonságot, erre a tanácstagok meggondolják magukat, és engedélyezik a döntő megtartását. A döntőn a Farkasdenevérek csalásokra alapozott küzdőmodora kibukkan, folyton sportszerűtlen magatartást tanúsítanak, és még a bírók is egy követ fújnak velük. "Kiütéssel" legyőzik a Tűzmenyéteket és már ünnepelnének, amikor egyenlőségiek támadják meg az arénát. A Farkasdenevérek mindhárom tagját megfosztja Amon az idomítási képességétől, aki bejelenti a forradalom kezdetét, és hogy ezentúl az egyenlőségi mozgalom már nem a föld alatt lapul, hanem nyíltan harcol az idomárok "elnyomása" ellen. Lin üldözőbe veszi a távozó Amont, de nem sikerül elfognia őt.

        Az Idomárarénát bezárják a történtek után, amivel Makóék az utcára kerülnének, hiszen az emeleten laknak. Korra elintézi Tenzinnél, hogy a Légtemplom-szigeten lakhassanak, de Asami megelőzi őket, és a birtokára hívja őket. Lin Beifong nyomozást kezdeményez az aréna elleni támadás kapcsán, és bizonyítékokat talál a Káposztagyár ellen, mely a Jövő Iparának legfőbb versenytársa, a cégtulajdonost, az Aang Avatar idejében élt káposztaárus fiát, Lau Gan-Lant letartóztatják. Mako és Bolin élvezik az életet a hatalmas és elegáns Sato-birtokon. Korra is velük tart kicsit a szórakozásban, és közben kihallgat egy gyanús telefonbeszélgetést, amit Hiroshi Sato folytat valakivel. Elmondja a gyanúját Lin Beifongnak és Tenzinnek is, akik házkutatást tartanak a Sato-birtokon és az összes gyárban és raktárban, de nem találnak semmi terhelőt. Korra megtudja Tenzintől, hogy elvileg Hiroshi Satónak lenne elég indítéka az egyenlőségiekkel való együttműködésre, mert a feleségét évekkel korábban megölte az Agni Kai Triad, egy tűzidomárokból álló bűnbanda, emiatt valószínűleg meggyűlölhette az idomárokat. Egy munkás kapcsolatba lép Beifongékkal és megemlíti, hogy van egy titkos gyár a birtokon a föld alá rejtve. Ismét megjelenik a rendőrség a birtokon, ezúttal siker koronázza a nyomozást: megtalálják a titkos üzemet és az újonnan kifejlesztett, mecha nevű szuperfegyvereket is. De csapdába esnek, mert Hiroshi már várt rájuk néhány chi-blokkolóval együtt. A fémidomár rendőröket sajnos fogságba ejtik és elviszik, de az Avatar Csapat megküzd Satóval és embereivel. Asami, aki a felszínen várta addig a házkutatás végét, türelmetlenül lemegy Makóval és Bolinnal együtt és szembesül a keserű igazsággal, hogy az apja egyenlőségi. Az öreg Sato arra hivatkozik, hogy az idomároknak köszönheti szeretett felesége halálát, és bizony nehezére esett évekig a kedélyes, kedves álarcot viselnie az idomárok előtt, ahányszor találkozott velük. Kéri a lányát, hogy az tartson vele, de Asami megtagadja az apját, és a feléje nyújtott elektromos kesztyűvel megrázza őt. Ezután eltűnnek a helyszínről. Lin be akarja adni a lemondását, hogy ne kösse őt a törvény, ha az emberei megmentésére siet.
        Az új rendőrfőnök egy Saikhan nevű fémidomár lesz. Asami a Légtemplom-szigeten talál menedéket, hiszen nem maradhat a Sato-birtokon. Az új rendőrkapitány maximálisan támogatja Tarrlok tanácsos terveit, hogy letörhesse a forradalmat, gyakorlatilag szabad kezet ad az akciócsoportjának. Tarrlok kifejezi Korrának abbéli reményét, hogy ismét beáll az osztagába, de az Avatar erre nem hajlandó, mert gátlástalan törtetőnek tartja Tarrlokot. A tanácsos erre a lány orra alá dörgöli, hogy még nem kész Avatar, és ha már nem tagja az akciócsoportnak, ne keresztezze az útját. Korra erre úgy dönt, hogy saját maga fog igazságot szolgáltatni az Avatar Csapattal együtt. El is fognak néhány szökevény chi-blokkolót, akiket átadnak a kiérkező rendőrségnek, de Tarrlok is megjelenik, aki megismétli figyelmeztetését. Korráék azonban fittyet hánynak rá, és amikor tudomást szereznek a forradalmárok állítólagos fegyveres tüntetéséről, a helyszínre mennek, de kiderül, hogy a tömegben senkinél sincs fegyver és csak az áram visszakapcsolását akarják elérni, tudniillik Tarrlok olyan intézkedéseket foganatosított a nem-idomárok ellen, amelyekkel már az alapvető polgári szabadságjogokat korlátozza. Korra követeli a helyszínen tartózkodó tanácsostól, hogy kapcsoltassa vissza az áramot és hagyja békén az ártatlan polgárokat, de Tarrlok fenyegetően reagál erre, majd letartóztatja előbb Asamit, utána a tiltakozó Makót és Bolint is, Korrát pedig csak azért nem, mert a lány idejében visszafogja a dühét. Persze ettől függetlenül nem nyugszik bele a barátai indokolatlan letartóztatásába, segítséget kér Tenzintől, de Saikhan nem hajlandó felülbírálni Tarrlok intézkedését. Ezután Korra rátör Tarrlokra egy este a városházán, és szemére veti, hogy csak erősíti Amon pozícióit azzal, hogy megfélemlíti a nem-idomár lakosságot, emellett követeli a barátai és az összes többi ártatlanul fogva tartott ember szabadon engedését. Tarrlok megelégeli a lány konokságát és harcba bocsátkozik vele. Azonban vesztésre áll, mert Korrának három elem is a rendelkezésére áll. Végső kétségbeesésében Tarrlok leleplezi magát – ő ugyanis nemcsak vízidomár, hanem vérhajlító is. Kiüti Korrát a képességével, majd kocsira rakja őt és egy rejtekhelyre hurcolja a hegyekbe.
        Korrának már korábban is voltak látomásai, amelyekben Aang szerepelt, ezekről egyszer beszélt is Tenzinnek. Ő akkor azt tanácsolta, hogy próbáljon meditálni ezeken a látomásokon, hátha ilyen módon akar Aang kapcsolatba kerülni Korrával. A lány, amíg fogságban sínylődik, megpróbálkozik a meditációval – és sikerül neki! Aang felidézi neki azt az eseménysorozatot, amely negyvenéves korában esett meg vele, mint a Köztársaság egyik alapítójával. A rendőrséggel együtt ő is megjelent, hogy őrizetbe vegyék Yakone-t, Köztársaságváros legveszélyesebb bűnözőjét, aki víz-és véridomár volt, és bandájával együtt sok bűntettért volt felelős. Yakone-t a tanács jogerősen életfogytiglani börtönre ítélte, ám az ítélet kihirdetésekor Yakone az összes jelenlevő vérét meghajlította, és így kiszabadította magát. Csakhogy Aang üldözőbe vette és megállította szökés közben, majd életében másodszor élt azzal a képességgel, hogy elvette egy idomár erejét, megfosztotta Yakone-t a hajlítási képességétől – az első személy Tűz Ura Ozai volt, akivel még gyerekként bánt el Sozin üstökösének eljövetelekor. Korra mindebből leszűri, hogy Tarrlok Yakone fia, de azt még nem érti, hogy mi történt Yakone tönkretétele után. Tarrlok ezalatt beállítja a helyszínt a városházán, később azt mondja a rendőröknek, hogy amikor Korra eljött hozzá, hirtelen rájuk törtek az egyenlőségiek és ők vitték magukkal Korrát. A rádió is tudósít erről az állítólagos támadásról, és ezt Lin Beifong is hallja. Kihozza a börtönből Makóékat, hogy együtt megkeressék Korrát meg az elfogott rendőröket, Tenzin is segít ebben. A rendőröket megtalálják a város alagútrendszerében, de az Avatart persze nem. Kérdőre vonják a chi-blokkolókat, akik elmondják, hogy kivételesen nem ők a hunyók. Tenzin rájön, hogy Tarrlok rabolta el Korrát, őket pedig becsapta. Sietnek Tarrlokhoz és szembesítik tettével, de ő kiüti mindannyiukat véridomítással és elmenekül a rejtekhelyére. Ott az Avatar közli vele, hogy ismeri a titkát, ahogy szemlátomást már mindenki más is. Tarrlok ezután távozna, de hívatlan látogatókat kap – Amont és néhány emberét. Tarrlok vérhajlítással kifekteti a chi-blokkolókat, de Amonnal meglepő módon nem bír, aki földre küldi a tanácsost és elveszi az erejét. Az embereit az Avatárért küldi, de ő túljár az eszükön és legyőzi őket, majd megpróbálja utolérni Amont, aki épp magával viszi Tarrlokot, meg akarja állítani, de ahogy Amon feléje tart, inkább elmenekül tőle. Menekülés közben megbotlik és elveszti az eszméletét, később a medvekutyája találja meg, aki leviszi őt a városba, a barátaihoz.
        Miután Korra magához tér, elmeséli mindazt, amit Aang üzent neki. Az egyenlőségiek támadást indítanak a város ellen, elrabolják Tenzin kivételével az összes tanácsost, és léghajókról bombázzák az épületeket. Megtámadják a rendőrkapitányság épületét is, ahová Tenzin sietve megérkezik. Gyorsan elküldet egy táviratot az Egyesült Erők parancsnokának, Iroh tábornoknak, hogy siessen a város megmentésére. Az emberekkel kimenekülnek az épületből, de kint már mecha tankok várják őket. A harcban Tenzinék veszítenek, és már majdnem elviszik őket, de jönnek Korráék, és megmentik őket. Támadás éri a Légtemplom-szigetet is, ami nagyon aggasztja Tenzint, hiszen ott él a családja. Ráadásul pont a támadás alatt indul meg Pemánál a szülés. De nincs minden veszve, mivel ott van Lin, akit korábban Tenzin kért meg, hogy vigyázzon mindenkire, és a Fehér Lótusz is résen van. Elhárítják a chi-blokkolók támadását, amiben nagy szerepe van Tenzin három gyermekének: Jinorának, Ikkinek és Meelónak is. Pema rendben megszüli kisfiát, aki a Rohan nevet kapja. De további léghajók érkeznek, ezért a családnak menekülnie kell, Lin kíséri őket. Ő azonban otthagyja az égi bölényt, amin Tenzin és családja menekül, és megpróbálja fémidomítással tönkretenni az üldöző léghajókat, de elcsípik őt, majd Amon elé viszik, aki megfosztja őt az erejétől.
        Az egyenlőségiek teljesen ellenőrzésük alá vonják a várost, ahol is az idomár népességet minden jogától megfosztják. Mako és Korra együtt kémkednek az egyenlőségiek között elvegyülve, amúgy is elég sokat vannak együtt mostanában, és ennek nem örül Asami. Megérkeznek az Egyesült Erők hadihajói, de kellemetlen meglepetés várja őket: a part menti vizek el vannak aknásítva és az egyenlőségiek is megtámadják őket, mégpedig a levegőből, repülőgépekkel. A flotta nagy részét elsüllyesztik, ezért Iroh tábornok számára fontos, hogy a második hajóraj, Bumival, Tenzin bátyjával az élen, nehogy ugyanerre a sorsra jusson. Üzenetet küldenek Buminak, majd akcióba lépnek: Asami, Bolin és Iroh vállalja, hogy megsemmisítik az egyenlőségiek légierejét, Mako és Korra pedig Amonra hajt. Éppen kiszúrják őt, amint távozik a Légtemplom-szigetről, odamennek. De meglepő felfedezést tesznek. Ugyanis egy foglyot őriznek a szigeten, akire nem számítottak: Tarrlokot. Ő elmeséli élete történetét, és hogy Amonnal testvérek, aki ugyanúgy víz-és véridomár, eredeti neve Noatak. Apjuk, Yakone, megszökött a börtönből, visszatért az északi víz törzshöz, ahonnan származott, családot alapított. Később, miután felfedezte, hogy a fiai is idomárok, elhatározta, hogy megtanítja őket a véridomításra. Úgy tervezte, hogy fiai által fog bosszút állni az Avatáron, aki tönkretette őt egy életre, és általuk az övé lesz Köztársaságváros. Egy incidenst követően azonban Noatak nyomtalanul eltűnt és soha többé nem tért vissza a szüleihez. Yakone kénytelen volt lemondani a bosszúról, és pár évvel később meghalt, ahogy a felesége is. Tarrlok azonban, miután felnőtt, elkerült Köztársaságvárosba, bejutott a város tanácsába és az egyenlőségiek felbukkanásakor elérkezettnek látta az időt arra, hogy a forradalom letörésével a város megmentőjének szerepét játszhassa, ami által a város az ölébe hullhat. Korra megérti Tarrlokot ezek után és ki akarná szabadítani a volt tanácsost, de Tarrlok nem járul hozzá, mondván, hogy a bátyja nem tudhatja meg, hogy beszélt nekik. Tarrlok mindenesetre bocsánatot kér az Avatartól a bántásért, a tisztességtelen hatalomgyakorlásért.
        Bár Korra úgy hiszi, hogy Amont csaknem lehetetlen legyőzni, mivel nagyon erős véridomár, de az igazság birtokában talán az lesz a leghatékonyabb, ha a követői előtt leleplezik és hiteltelenné teszik őt. Megtudják, hogy az egykori arénában nagygyűlés lesz, ahová beszivárognak chi-blokkolónak öltözve. Amon éppen beszédet mond, amiben azt taglalja, hogy gyerekként egy tűzidomár megnyomorította őt, de az Avatar közbeszól és a tömeg előtt kikiáltja az igazat Amonról. Ő azonban látszólag megcáfolja ezt, amikor leveti maszkját és mindenki egy csúnya égési sérülést lát az arcán, ezt kénytelen takargatni a maszkkal. Korra alulmarad, menekülne, de Amon még marasztalja, és előhozatja a megkötözött Tenzint és családját. Amonnak az a terve, hogy mindegyiküket megfossza az erejétől, és így nem lenne több levegőidomár a világon. Korra ezt nem hagyhatja, és harcba száll Amonnal. Kiszabadítják a légidomárokat, majd elbújnak Amon elől. De ő véridomítással előszedi őket a rejtekükből, és bekövetkezik az, amitől Korra a legjobban rettegett mindvégig, Amon elveszi az erejét. A chi-blokkolók hadnagya észreveszi ezt, és egyszeriben Amon ellen fordul, mert mélyen megveti őt a hazudozásáért, hogy nem-idomárnak adta ki magát. De Amon legyőzi őt. Ezután Makótól is el akarja venni az erejét, aki fejvesztve menekül Korrát cipelve, de Korra valahogy összeszedi magát és léghajlítással megakadályozza ezt. Mind ő, mind Amon elámul ezen. Egy jól irányzott csapással az Avatar kiveti Amont a kikötő vizébe, ahol a vezér arcáról lemosódik a festék, ez volt az állítólagos égési seb. Hogy ne fulladjon meg, önkéntelenül is vizet idomítva a felszínre jön, és ezt látják az összesereglett emberek is, akik becsapva érzik magukat. Mako tűzcsapásokkal akarja megállítani, de Amon meglóg. Elmegy a Légtemplom-szigetre, és magával viszi az öccsét, Tarrlokot, hogy új életet kezdjenek, miután az egyenlőségi mozgalom immáron elbukott. De Tarrlok le akar zárni mindent, ezért a nyílt tengeren végez mindkettejükkel: felrobbantja a motorcsónakot, amiben utaznak. Korra azonban nem tud erről, így még sokáig gyötri a nyugtalanság, amikor Amonra gondol.
        Korrát a Déli-sarkon Katara próbálja meggyógyítani, de még ő, a legkiválóbb gyógyító sem képes visszaadni neki az idomítási képességet. A lány végtelenül el van csüggedve és ingerülten utasítja el Mako szerelmes közeledését. Bánatában sírni kezd a tengerparton, és erre Aang jelenik meg előtte teljes életnagyságban, mögötte pedig a korábbi Avatárok. Aang a lány homlokára teszi a kezét, és ahogy képes bárkitől elvenni az idomítási képességet, úgy ebben az esetben most visszaadja azt Korrának. Mako tanúja ennek, Korra pedig odarohan hozzá boldogan, és csak ekkor mondja neki: "Én is szeretlek." Végül az Avatar mindenki ámulatára visszaadja az idomítási képességet Lin Beifongnak, amiért mindenki nagyon büszke rá.
        <p></section >
        <h2  class="alcim"  id="Masodik"><br>2. Évad: Szellemek</h2><br>
            <section  class="karakteroldal">
                <p > <img src="képek/Korra/k2.png" class="kepek" alt="Korra 2. évad"> </p>
    <p>Amon bukása és halála után fél évvel vagyunk. Korra, miután az előző Avatar, Aang visszaadta neki az idomítási képességét, maga is visszaadta azt Köztársaságváros minden idomárjának, akiket korábban Amon megfosztott az erejétől (kivéve a bűnözőket). Korra szorgalmasan tanulja Tenzintől a levegőidomítást. A város tanácsa feloszlatta magát, mivel belátta, hogy végső soron igaza volt az egyenlőségi mozgalomnak annyiban, hogy tényleg nem képviselték Köztársaságváros lakosságának zömét, akik nem-idomárok. Raiko, egy nem-idomár politikus lett a Nemzetek Egyesült Köztársaságának első elnöke. Mako rendőr lett a városban, Bolin pedig hamarosan vonzó ajánlatot kap. Asami megpróbálja fenntartani a Jövő Iparát, miután apja börtönbe került az egyenlőségi mozgalomban betöltött szerepéért, de egyre nehezebben megy az üzlet, mert nem talál üzleti partnert. Azonban hamarosan megoldódik ez a probléma, miután megismerkedik Iknik Blackstone Varrick-kel, a déli víz törzs nem-idomár tagjával, aki dúsgazdag üzletember és feltaláló. Az ő pénzügyi segítségével szanálják a Jövő Iparát. Bolint is felkarolja az üzletember, mikor is felajánlja neki, hogy legyen mozgósztár, mert a mozgóban, ebben az új technikai vívmányban (lényegében olyan, mint a valóságban a film) rengeteg új lehetőség van.Közben kialakul a következő krízishelyzet, amit az Avatarnak meg kell oldania: a déli víz törzs kereskedelmi hajóit egyre gyakrabban támadják meg sötét szellemek. Erre a gondra Unalaq, az északi víz törzs vezetője, Korra nagybátyja hívja fel az Avatar figyelmét, amikor látogatóba érkezik a Déli-sarkra, a Gleccserszellemek Fesztiváljára. Unalaq rámutat arra, hogy a szellemek azért agresszívek, mert a déli víz törzs szinte teljesen elfelejtette spirituális gyökereit, túlzottan anyagiassá váltak. Unalaq a fesztivált is kritikával illeti, amely eredetileg szintén a spiritualitásról szólt, nem pedig a vásározásról meg a mértéktelen habzsolásról. Korrának kissé elege van már Tenzin bábáskodásából, és mikor egy sötét szellem rajta üt a fővároson, akivel egyedül Unalaq bír el, elhatározza, hogy megszakítja a tanító-tanítvány kapcsolatot Tenzinnel, és Unalaq tanítványa lesz, aki szintén erre biztatja, és örül, hogy megtaníthatja Korrának a szellemek tudományát.

        De Korra hamarosan rádöbben arra, hogy Unalaq a saját tisztességtelen céljaira akarta csak felhasználni őt a nagy tudása ellenére, ellenben Tenzin, bár nem mindig hatékony az ismeretek átadásában, végig Korráért tesz mindent. Fény derül közben az Unalaq és Korra apja, Tonraq közt fennálló feszült viszony okára is: Tonraqot száműzte apja, az északi törzsfő egy meggondolatlan tette miatt: kiirtott egy szellemek lakta erdőt, miközben barbár hordákat üldözött, akik előzőleg megtámadták a fővárost. Tonraq ezután a Déli-sarkra utazott, ott lelt új otthonra, később a déli törzs egyik prominens személyisége lett. Unalaq nem próbálta visszafogni forró fejű fivérét, hagyta, hogy Tonraq elpusztítsa a szellemek erdejét, így ő lett északon a törzsfő apjuk halála után.Unalaq megnyittatja Korrával a Déli-sarkon lévő, szellemvilágba vezető átjárót, mondván, hogy ezzel helyre fog állni a szellemi világ egyensúlya. Korra megteszi, de a visszatéréskor a déli fővárosban meglátják az északiak hadseregét. És ekkor árulja el Unalaq, hogy a déli átjáró megnyitása csak a kezdet volt a terveiben, a következő lépés a víz két törzsének egyesítése lesz, északi vezetéssel.

        Az északi szárazföldi csapatok és a haditengerészet megszállják a Déli-sarkot, a megszállás tiltakozási hullámot indít el, ellenállási mozgalom jön létre Varrick és Tonraq vezetésével, polgárháború tör ki. Közeben Ikki eltűnt, Tenzin, Kya és Bumi elindulnak megkeresni, de Kya és Bumi vissazmentek a Déli Levegő templomba, így egyedül ment tovább Tenzin, hogy megkerrese Ikkit. Varrick emberei megpróbálják elrabolni Unalaqot, de a gyanú Tonraqra terelődik.

        Akit testvére perbe fogat és elítéltet, előbb halálra, majd hosszú börtönbüntetésre. A kegyelem arra szolgál, hogy Korra Unalaq pártjára álljon. Korra azonban kideríti, hogy a per koncepciós jellegű volt, a bíró Unalaq utasításai szerint járt el. Miután leleplezi nagybátyja hataloméhségét, Korra harcot indít ellene.

        A gyengébb déli seregek azonban nem bírnak az erősebb északi csapatokkal, ezért Korra segítséget kér az Egyesült Köztársaságtól, amit Raiko elnök elutasít, mivel szerinte a polgárháború a víz törzseinek belügye. Korra az elnök tudta nélkül az Egyesült Erők főparancsnokát, Iroh tábornokot kéri meg, hogy hadgyakorlat ürügyén vonuljon fel a déli felségvizeken, de a konspiratív találkozót az elnök zavarja meg, aki erről Makótól értesült, és hadbírósággal fenyegeti meg a tábornokot, ha kihajózik a honi kikötőből engedély nélkül. Mielőtt elbúcsúznak, Iroh azt javasolja az Avatarnak, hogy forduljon az édesanyjához, a Tűz Úrnőjéhez, ő talán küld majd sereget. Korrát azonban egy hatalmas sötét szellem támadja meg a nyílt óceánon, útban a Tűz Országa felé, miközben unokatestvérei, Eska és Desna is üldözik.

        Eskna és Desna közlik az apjukkal, hogy az Avatárt elragadtta egy sötét szellem és talán már meghalt. Közben Köztársoság városában zajlik az élet Bolin egy mozgókép( a mai film) sztárja lett, az előzetes nagy siker volt. Sajnos Varrict rossz híreket kapott, miután az előzetes sikeres volt, elrabolták a rakományait. Mako és Asami eldöntik, hogy ők majd megoldják az ügyet,de sajnos elterelés volt az egész, hogy Asami gyárát kirabolhasák. Mako rájött, hogy a háttérben Varrick áll, de mikor szembesítené a tényekkel épp ott volt Asami az aláírt szerződéssel így nem tudta elmondani az igazat. Később Korrét partra sodorja a víz a Tűz Országában, de emlékezetkiesése van.

        Gyógyítókhoz kerül, és a segítségükkel előző életeivel kerül kapcsolatba, majd találkozik az első Avatarral, Wannal, akinek történetéből megismeri, hogyan keletkezett az Avatarok ciklusa, amikor is Wan eggyé vált Raava-val, a fény szellemével. Tízezer évvel ezelőtt Wan véletlenül szétválasztotta Raavát és Vaatut, a sötétség szellemét, de hogy helyrehozza, amit elrontott, segíteni akart Raavának, hogy ismét lekössék Vaatut. Egy gigászi küzdelem során Wan, aki előzőleg magáévá tette a négy elem tudományát, összeolvadt Raavával, és így lett belőle az első Avatar, és végül az Idő Fájának odvába zárta Vaatut, valamint lezárta a szellemi átjárókat, hogy emberi lény nehogy megint kiszabadítsa merő tévedésből a sötétség szellemét. Korra felébred, immár mindenre emlékszik, és siet, hogy a bolygók közeli együttállása előtt lezárja a szellemi átjárókat. Unalaq végső célja ugyanis nyilvánvalóvá vált: egyesülni akar a kiszabadult Vaatuval, hogy ő legyen a Sötét Avatar.


        Korra át akar lépni a szellemi világba, hogy ott blokkolja az átjárót, ehhez Tenzin segítségét kéri, akihez ismét elszegődött tanítványként. Tenzin mindig azt hangoztatja, hogy sokat járt már a szellemvilágban, ezért tapasztalt szellemi vezetőnek tartják. Később, mivel sehogy sem tud Korrával átlépni, beismeri, hogy valójában sosem járt ott még. Ellenben Tenzin nagyobbik lánya, Jinora természetes módon, erőlködés nélkül át tud jutni, amit apja nehezen dolgoz fel. Korrával együtt meg akarják keresni az átjárót, ami nem megy simán, mert egy időre elveszítik egymást. Végül megtalálják az átjárót, de megjelenik Unalaq is, aki idomítással legyőzi őket, mivel Korra nem tud idomítani (ugyanis nem az átjárón át érkezett, hanem meditálással lépett be, így elvész az idomítási képesség). Unalaq túszul ejti Jinorát és kényszeríti Korrát, hogy nyissa meg az átjárót, ha nem akarja, hogy Jinora lelke örökké a szellemvilágban maradjon.

        Varrick machinációkkal akarja elérni, hogy a déli víz törzs támogatást kapjon. Már korábban is eljátszotta azt, hogy a Tripla Terrort, Köztársaságváros egyik bűnbandáját használta fel arra, hogy a háború tovább eszkalálódjon. Mako is emiatt ütötte meg a bokáját, mert együttműködött a bűnbandával, és korrupció gyanújával letartóztatták. Pedig ő figyelt fel arra, hogy amikor robbantásos merényletet követtek el a Déli Víz Törzs Kulturális Központja ellen, egy tűzidomár távozott a helyszínről, aki pontosan olyan detonátort hagyott ott, amilyet Varrick cégei is gyártanak. Az akciót maga Varrick rendelte meg, hogy aztán megvádolhassa az északi víz törzset. Szintén Varrick állt a hátterében annak, hogy Asami raktárát kirámolta a Tripla Terror, ezzel lehetetlen helyzetbe hozva az ifjú üzletasszonyt. Később pedig el akarja raboltatni Raiko elnököt, ebben néhány déli vízidomár segít neki, akik északi katonáknak vannak öltözve, hogy az északi törzsre terelődjön a gyanú. Az emberrablási kísérletre a "Nuktuk, a Dél bajnoka" című mozgósorozat utolsó részének vetítésén kerül sor, melynek főszereplője Bolin. A sorozat propagandacélokat szolgál, Varrick ezzel is az elnökre próbál hatni, hogy adjon katonai támogatást. De hiába, Bolin a premieren megmenti Raikót, aki még ezek után sem akar segíteni. Viszont Mako kiszabadul a börtönből, amiért korábban figyelmeztette a rendőrséget Varrick cselszövéseire, bár akkor még senki sem hitt neki. Mako ezután már nem járőr, hanem nyomozó lesz. Varricket letartóztatják, titkárnője, Zhu Li a börtönbe is követi őt, ahol elképesztő luxusban vannak.

        Tonraq és Unalaq összecsapnak, előbbi vereséget szenved. Unalaq siet a szellemvilágba, hogy az együttállásra felkészülhessen. Gyermekei, Eska és Desna feltartóztatják Makót és Bolint, míg ő az Avatarral küzd meg. Korra közben le akarja zárni az átjárót, de az együttállás bekövetkezik, késő már, és Vaatu kiszabadul, majd egyesül Unalaqkal. Ez még Eskát és Desnát is megdöbbenti, akik eddig segítették apjukat. Korra mellé állnak, és segítenek neki a küzdelemben. De Unalaq Vaatuval egyesülve kiszívja Korra testéből Raavát, és legyőzi. Ezzel Korra elveszti a kapcsolatát az összes korábbi Avatarral.

        Unalaq, mint Sötét Avatar Köztársaságvárost fenyegeti. Korra, miután magához tér, nem érez semmi reményt, de Tenzin lelket önt belé, és rábeszéli őt arra, hogy egyesüljön az univerzum kozmikus energiájával. Az egyesülés után Korra egy gigantikus formát vesz fel, és megküzd a nagybátyjával. Legyőzi őt, és megtalálja a testében Raavát, akivel újra egyesül, ám a korábbi Avatárokkal való kapcsolatát már nem képes újjáéleszteni. Unalaq meghal az összecsapásban.

        Végül Korra a Déli-sarkon jelenti be a polgárháború végét, az északi csapatok hazatérését, és azt, hogy a Déli Víz Törzs kimondta teljes függetlenségét (eddig névleg az északiak vezetése alatt álltak), valamint hogy apját, Tonraqot törzsfővé választotta a Vének Tanácsa. A szellemi átjárók nyitva maradtak, ezáltal emberek és szellemek kölcsönösen átjárhatnak egymás világába.
        <p></section>
        <h2 class="alcim" id="Harmadik">3. Évad: Változás</h2>
                <section  class="karakteroldal">
                    <p > <img src="képek/Korra/k3.png" class="kepek" alt="Korra 3 évad"> </p>

    <p>Szellemek lepik el a világot, és az emberekkel való együttélésük nem mindig megy simán. Köztársaságvárosban egy egész szellemvadon nőtt, ami egyre jobban idegesíti a lakókat.

        Az együttállásnak más hozadéka is van: bármilyen hihetetlen, de néhány ember levegőidomítási képességet észlel magán, közéjük tartozik Bumi is, Tenzin bátyja. Hamarosan több levegőidomárról is hírek futnak be, aminek Tenzin nagyon örül, hiszen 170 év után lehetőség nyílik a Levegő Népének újjászervezésére. Korra vállalja a feladatot, hogy megkeresse és meggyőzze ezen újdonsült idomárokat, hogy Tenzintől tanuljanak, hogy megfelelően élhessenek a képességükkel. Miközben egy megzavarodott levegőidomárt ment meg, Raiko elnök türelme elfogy a szellemek miatt, és úgy összezördül Korrával, hogy végül száműzi őt Köztársaságvárosból.

        A Fehér Lótusz szigorúan őrzött börtönben tart egy bűnözőt, Zaheert, aki az együttállás hatására szintén levegőidomár lett. Mivel már korábban is Laghima guru, egy levegőidomár-mester tanait követte, könnyedén él az új képességével és megszökik a fogságból, hogy megszöktesse társait, akik a világ több pontján vannak börtönben: barátnőjét, P'Lit az Északi-sarkon őrzik, hogy a hidegben ne tudjon tüzet idomítani, társát, a földidomár Ghazant faketrecben tartják, hogy ne idomíthasson földet, Ming-Huát, egy vízidomár nőt pedig egy vulkán torkában őrzik, ahol a forróság miatt nem képes a vízidomításra. Zaheer szökéséről a Fehér Lótusz informálja Zuko nagyurat, az egykori Tűz Urát, aki ezután megszemléli P'Lit és a fogvatartása körülményeit. Bár a Fehér Lótusz készültségben van, Zaheerék mégis képesek kiszabadítani P'Lit és az Avatar keresésére indulnak.

        Korra közben a Föld Királyságába utazik, mivel több újdonsült levegőidomárról is hírek érkeztek onnét. A fővárosban, Ba Sing Sé-ben felkeresi a királynőt és az idomárokról érdeklődik tőle, de ő azt mondja, nem tud róluk semmit. A királynő hazudik, mert a levegőidomárokat erőszakkal besorozta a hadseregébe és a titkosrendőrség, a Dai Li tagjai elit katonákká akarják kiképezni őket. A királynőnek meggyőződése, hogy a levegőidomárok a Föld Királysága állampolgárai lévén az ő alattvalói, ezért engedelmességgel tartoznak neki, és ezért akarja a hadseregében tartani őket. Korra elvállalja, hogy segít beszedni az adót a királyság egyik nyugtalan részén, de amikor rájön, hogy a királynő hazudott neki a levegőidomárokról, elhatározza, hogy megszökteti őket. De mivel Korrát veszély fenyegeti a szökött bűnözők részéről, Lin Beifong, Köztársaságváros rendőrfőnöke kíséri őt az útján.

        Miután a levegőidomárokat sikerül megszöktetni a Dai Li titkos kiképzőtáborából, Korra a királyság Zaofu nevű városába veszi az irányt, ahonnan egy újabb levegőidomárról érkezett hír. Ezt a várost az ún. fémklán lakja, akik mindent fémből építettek. A fémidomárok vezetője Suyin Beifong, Lin féltestvére. Ők ketten Toph Beifong lányai, Toph pedig az előző Avatar, Aang földidomár mestere és barátja, valamint a világ első fémidomárja, később Köztársaságváros első rendőrkapitánya. A megérkezéskor Lin nem akarja megmutatni magát, de később kénytelen ő is előjönni. Az ok: fiatal éveikben Lin és Suyin között nézeteltérések támadtak, Lin rendőr lett, akárcsak az anyja, ellenben Suyin léha életet élt és a törvénnyel is szembekerült. Később Suyin férjhez ment egy Baatar nevű tudóshoz, és létrehozta Zaofut, a fémidomárok városát, amely szavai szerint a világ legbiztonságosabb városa, és megnyugtatja Korráékat, hogy itt biztonságban van a rá vadászó bűnözőktől. A levegőidomár nem más, mint Suyin egyetlen lánya, Opal, aki beleegyezik abba, hogy Tenzintől tanuljon. Lin az azonnali távozást ajánlja a Avatar biztonsága érdekében, de Suyin ismét megnyugtatja a társaságot.

        A biztonságnak azonban hamar vége lesz, mert Zaheer és bandája megtámadja a várost. Sikerül visszavonulásra kényszeríteni őket, de senki sem érti, hogyan tudtak behatolni az erős védelmi rendszer ellenére. Aiwei, a város igazlátója és Suyin jobbkeze kikérdezi az őrséget, eredménytelenül. Makónak viszont az a gyanúja, hogy maga Aiwei lehet a sáros, az egyetlen ember Zaofuban, akinek titkai lehetnek. Valóban, miután Korra, Mako, Bolin és Asami behatolnak Aiwei lakására, egy titkos alagutat találnak a lakás alatt, ezen át hatoltak be Zaheerék. Aiwei éppen hazajön, és kérdőre vonja a fiatalokat, aztán leleplezi magát és elmenekül az alagúton, amit beomlaszt maga mögött. Suyint sokkolja Aiwei árulása, miközben végig maximálisan bízott benne. Az Avatar csapat Aiwei nyomába ered, hogy így Zaheerra találjanak, válaszokért.

        Korráék a Ködös Pálma Oázisban bukkannak rá Aiwei-re, egy panzióban. Miután egész nap hiába figyelik a szobáját, bemennek hozzá. Aiwei meditációban ül az ágyon. Korra rájön, hogy Aiwei lelke a szellemvilágban van, ezért ő is meditálni kezd, hogy kövesse. A szellemvilágban Korra egy korábbi információt felhasználva Xai Bau berkébe megy, és ott találja Aiweit, aki Zaheerral találkozik éppen. Az igazlátó biztosítja Zaheert, hogy senki sem követte és az árulásáról sem tudnak, de Korra megmutatja magát, Zaheer pedig az Elveszett Lelkek Homályába taszítja Aiwei lelkét. Korra ezután magyarázatot követel, hogy miért akarták őt elrabolni kiskorában, erre Zaheer felfedi a Vörös Lótusz létezését, amely egy titkos szervezet, mint egykor a Fehér Lótusz. Az utóbbi egy tagja, Xai Bau kilépett és létrehozta a Vörös Lótuszt, mert szerinte a Fehér Lótusz helytelenül cselekedett, amikor nyilvánosan kezdett működni és a mindenkori Avatar szolgálatába állt. A Vörös Lótusz egy anarchista szervezet, melynek célja, hogy megszüntesse a kormányok hatalmát. Korra meglepődik, mikor Zaheer elmondja neki, hogy a nagybátyja, Unalaq is a szervezet tagja volt, és Zaheerék az ő utasítására próbálták elrabolni Korrát. Unalaq azonban minden hozzá vezető nyomot eltüntetett, és hagyta, hogy Zaheert és társait elfogja a Fehér Lótusz Tenzin, Sokka, Zuko és Tonraq vezetésével.

        Zaheer a meditáció közben elárulta társainak Korráék hollétét, így ők rajtaütnek az Avatar Csapaton. Asami elmenekül Korra testével Naga hátán, Mako és Bolin addig megpróbálják feltartani Zaheer társait, de nem járnak sikerrel, elfogják őket. Korrát és Asamit pedig a Föld Királynőjének katonái ejtik fogságba, mivel a királynő kérdőre akarja vonni az Avatart a légidomárok megszöktetése miatt. Korra nem akarja, hogy a királynő elé vigyék, ezért Asamival megtámadják a katonákat, de a léghajójuk lezuhan a sivatagban. A katonákat a maguk oldalára állítják és eszkábálnak egy homokvitorlást a roncsokból, így jutnak el egy oázisba, ahol Zukóval, Tonraqkal és Linnel találkoznak.

        Zaheerék átadják a Föld Királynőnek Makót és Bolint, akiket a királynő fogságba vet. Zaheer üzletet akar: az Avatart, cserébe a levegőidomárokért. A királynő elfogadja az ajánlatot. Később Zaheer beront a királynőhöz és megöli őt, amit közöl a néppel is. Ba Sing Se városában eluralkodik a káosz. Zaheer kiengedi a börtönből Makóékat, de el kell vinniük egy ultimátumot Korrának: ha nem adja át magát önként Zaheernak, akkor a levegőidomárok pórul járnak.

        Makóék átadják az üzenetet Korrának, amikor újra találkoznak, Korra megpróbál rádión szólni az északi levegőtemplomba, de mire eléri Tenzint, már késő, Zaheerék megtámadják a templomot. Tenzin és társai ellenállnak, de a gazemberek legyűrik őket. Zaheer rádión kapcsolatba lép Korrával és követeli tőle, hogy önként adja át magát, amire Korra rááll. Tonraq, Lin és Suyin vállalják, hogy résen lesznek, Mako és Bolin pedig elmennek a levegőidomárokért. De Zaheerék tőrbe csalják őket, Mako gyorsan figyelmezteti Korrát, hogy a levegőidomárok nincsenek a templomban, és ne adja fel magát, de késő. Korra ettől függetlenül megpróbál megküzdeni Zaheerral még leláncoltan is, de elbukik és Zaheer elrepül vele – Laghima tanainak követése meghozta gyümölcsét, no meg P'Li, a robbanásidomárnő halála is adott egy lökést ehhez, hiszen így már nem kötötték földi kapcsolatok.

        Korrát leláncolják, és a Vörös Lótusz néhány fémidomár tagja egy fém alapú mérget ad be neki, amitől önkéntelenül előjön az Avatar Állapot. Zaheer és társai ebben az állapotban akarnak végezni Korrával, hogy az Avatárok ciklusa örökre megszakadjon. Korra ellenáll, és eltépi láncait, majd harcba száll Zaheerral. Az Avatar Csapat Zaheer társaival veszi fel a harcot. Ming Huát Mako öli meg villámmal, Ghazan pedig öngyilkos lesz. Ezután kiszabadítják a levegőidomárokat, akikre a Vörös Lótusz tagjai vigyáznak. Korra ezalatt élethalálharcot vív Zaheerral, de vesztésre áll, a méreg egyre jobban kifejti hatását. A levegőidomárok egy nagy forgószelet keltenek, és így kapják el Zaheert, akit rögtön foglyul ejtenek. Korra alig él, Suyin Beifong kiidomítja a testéből a mérget, de lebénul.

        Korra tolószékbe kényszerül, visszaviszik őt Köztársaságvárosba. Raiko elnök bocsánatot kér tőle, amiért kiutasította őt a városból. Zaheer ismét börtönbe kerül, a Vörös Lótuszt pedig terrorszervezetté nyilvánítják. Jinorát légidomármesterré avatják, Tenzin pedig bejelenti, hogy az újjászülető Levegő Népe az egész világon a stabilitást és a békét fogja előmozdítani.
        <p></section>
        <h2 class="alcim" id="Negyedik">4. Évad: Egyensúly</h2>
                    <section  class="karakteroldal">
                        <p > <img src="képek/Korra/k4.png" class="kepek" alt="KOrra 4 évad"> </p>

    <p>Három év telt el azóta, hogy Korrát kis híján megölte a Vörös Lótusz. Sokáig lábadozott a Déli-sarkon, miközben az idős Katara gyógyította őt és irányította a rehabilitációját. Mikor jobban lett, elhagyta a Déli-sarkot és a világot járta. De folyton látomások kínozzák, és testileg sem jött helyre száz százalékosan.

        A Föld Királyságában eluralkodott a káosz az 53. uralkodó, Hou Ting halála óta, akit Zaheer ölt meg. Örököse, Wu herceg, aki a korábbi Föld királya, a Dai Li által sokáig befolyásolt Kuei dédunokája, kénytelen volt emigrálni az országból, és az Egyesült Köztársaságban keresett menedéket, ahol is Mako lett a kísérője és bizalmasa. Wu szeretné átvenni a királyság vezetését, de Kuvira, aki korábban Suyin Beifong egyik katonája volt, ellene dolgozik. Kuvira megszünteti a királyságot, és létrehozza a Föld Birodalmát, magát pedig teljhatalmú katonai diktátorrá nyilvánítja. A neki hűséget fogadó kisebb államoknak megígéri, hogy a központi kormánytól elegendő ellátmányt és védelmet kapnak. Terve végső soron az, hogy minden olyan területet visszafoglaljon, ami egykor a Föld Királyságához tartozott, így az Egyesült Köztársaságot is, amelyet Aang Avatar és Tűz Ura Zuko hozott létre a Tűz Népe által létesített kolóniákból. Egyszóval most igen nagy szükség van Korrára, de ő nincs a közelben. Még mindig a világban utazgat, és nem tökéletes az idomítási képessége.

        Ám az Avatart a szellemvadon hívja, és ott egy régi jó ismerőssel találkozik – Toph Beifonggal, a legendás föld-és fémidomárral. Toph egyedül él a mocsárban, régóta visszavonult a rendőrségi munkától és a világ más egyéb dolgaitól. Hosszas rábeszélésre elvállalja, hogy segítsen Korrának az állapota további javításában. Edzi az idomítási képességét és az akaraterejét, kitartását is, a leckék nem túl kellemesek, mivel Toph egész életében kifejezetten örömét lelte az Avatarok kínzásában, ahogy ő maga vallja. Korrát időnként ellenségeinek emlékei gyötrik, harca Amonnal, Unalaqkal és Zaheerral újra és újra kibillenti egyensúlyából. Toph rámutat arra, hogy Korra még nem tette túl magát ezeken, ezért szükséges, hogy ne bánkódjon tovább azon, ami már megtörtént.

        Tenzin közben a gyermekeit, Jinorát, Ikkit és Meelot Korra keresésére küldi, mert Kuvira hatalomgyakorlása egyre aggasztóbb a világ számára. A gyerekek sokáig nem érnek el eredményt, de amikor Toph a mocsárban arra utasítja Korrát, hogy próbáljon kapcsolatba kerülni szeretteivel a mocsár legnagyobb fájának gyökérzete révén, Jinora érzékeli a jelenlétét és rábukkannak. Hazahívják Korrát, akinek előtte van egy feladata: megszabadulni a méreg maradékától, mivel Suyin nem végzett tökéletes munkát. A művelet sikerül, Korra végre képes megidézni az Avatar Állapotot, ezután távozik a mocsárból Tenzin gyermekeivel és szívében hálával Toph iránt.

        Korra azt kéri a gyerekektől, hogy menjenek egyenesen Zaofuba. Tudja, hogy segítenie kell Suyinnak, főleg, miután Kuvira a város alá küldte jól felszerelt hadseregét. A diktátor azt követeli Suyintól, hogy ismerje el a fennhatóságát a városállam felett, de Su ezt megtagadja, mert a Föld Birodalma más államai példájából tudja már, milyen is Kuvira uralma. Még fia, ifjabb Baatar, aki Kuvira jegyese lett, sem tudja őt meggyőzni. Kuvira ezután erő alkalmazására szánja el magát.

        Megérkezik az Avatar, és Suyinnal beszél. A matriarcha elmondja Korrának, hogy a Föld Királynő halála után a világ többi vezetője őt akarta felkérni a királyság vezetésére, de ő nem akarta vállalni, mert nem vágyott uralkodói babérokra. Kuvira viszont, aki a városállam hadseregében szolgált akkor, kihasználta a lehetőséget, többeket maga mellé állított, például Bolint, ifjabb Baatart, és Varricket, ez utóbbi a börtönből való szabadulása óta Zaofu vendégszeretetét élvezte. Kuvira rendet teremtett Ba Sing Se városában és szerte a Föld Királyságában, így elnyerte a többi állam támogatását, és szavát vették, hogy az új király trónralépésekor lemond. Ezt azonban "elfelejtette" betartani és azóta is makacsul ragaszkodik a hatalomhoz, sőt az ország területének növeléséhez. Varrick, aki kiváló tudós, most a diktátor utasítására szellemindák felhasználásával egy szupererős fegyvert fejleszt. Egy balul sikerült kísérlet után azt javasolja Kuvirának, hogy ne folytassák a fejlesztést, de Kuvira nem tűr ellentmondást. Bolin szintén Kuvirát szolgálja, de Varrickhez hasonlóan neki is kétségei támadnak a diktátor módszereit illetően. Együtt akarnak megszökni, de visszahozzák őket. Kuvira ismét parancsot ad a fegyver fejlesztésére, Bolint pedig átképzőtáborba küldi. Varrick titkárnője, Zhu Li hűséget fogad, hogy elkerülje a deportálást – mint később kiderül, a hűsége nem igazi.

        Korra tárgyalni akar Kuvirával, ami megtörténik. Fegyverszünetben állapodnak meg, Kuvira addig hozzájárul, hogy Korra meggyőzze Suyint, de utóbbi megelőzi őket, mert lopva rá akar támadni Kuvirára. A próbálkozás eredménytelen, Suyin, a férje és két fia fogságba esik. Kuvirát felháborítja a fegyverszüneti megállapodás megszegése, és a seregét a városra akarja zúdítani, de Korra párviadalt ajánl, amit végül elfogad. Ha Korra győz, a város elkerüli a megszállást, ha Kuvira győz, a város kénytelen lesz fejet hajtani előtte. Korra még mindig nem tud tökéletesen harcolni, és alulmarad a küzdelemben. A diktátor serege elfoglalja Zaofut, a lakosság zöme hűséget fogad neki, de idősebb Baatar és Huan, a második fiú a sorban, erre nem hajlandók. Varrick és Bolin ezalatt megszöknek a vonatról, ami az átképzőtáborba viszi őket, és Köztársaságváros felé menekülnek, hogy figyelmeztessék a vezetőket Kuvira terveiről.

        Korra visszatér Köztársaságvárosba, ahol Tenzinnel, Makóval és Asamival is találkozik. Asami időközben néhányszor meglátogatta börtönben ülő apját, és fokozatosan felkészült a megbocsátásra. Mako nehezményezi, hogy Korra nem írt neki levelet az eltelt három évben. Mindezt egy ebéd előtt beszélik meg, amelyen Wu herceg is részt vesz. Wu kimegy a mosdóba, ez egyszer egyedül, és ebből baj történik, mert Kuvira ügynökei elrabolják. Korráék az emberrablók nyomába erednek, akik a város főpályaudvarára viszik a herceget. Sikerül felszállniuk az egyik vonatra, és kiszabadítják Wut egy kis küzdelem után. Bolin és Varrick közben néhány dezertőr fogságába esik, akik Kuvira egyik átképzőtáborából szöktek meg, tűz-és vízidomárok vegyesen. Azt hiszik, Bolinék is a diktátorral vannak, de belátják, hogy ők is tőle szöktek meg. Összefognak, hogy átlépjék a Föld Birodalmának határát, de egy határátkelőnél felismerik őket, és harcolniuk kell az őrséggel. Legyőzik őket, és együtt menekülnek tovább.

        Wu herceget Asami házában szállásolják el ideiglenesen. Jinora zavart érez a szellemmocsár erejében, miután Köztársaságvárosban egy csapat turistát elragadnak a szellemindák, Korra utánajár a dolognak, és megtudja, hogy Kuvira serege szellemindákat szüretel, így keletkezik a zavar. A felfedezést az éppen tanácskozó világvezetők tudomására hozzák, és az időközben befutó Varrick és Bolin is elmesélik, hogy milyen projektben segítettek Kuvirának. Felismerve a veszélyt, Raiko elnök elrendeli a határok megerősítését. Korra szeretné kiszabadítani az indák fogságából Jinorát és a többieket, de képtelen rá, egyfolytában akadályozzák a látomásai, nem tud tőlük átlépni a szellemvilágba. Őrültnek hangzó ötlete támad: talán az a személy segíthet, aki maga okozza mindezt – Zaheer. Sikerül rávennie Tenzint, hogy elintézzen egy találkozót a börtönben levő Zaheerral. A fogoly ráérez arra, hogy az Avatar miért kegyeskedett meglátogatni őt, és kifejti neki kettejük élethelyzetét: ő le van láncolva, bár tud repülni és sok időt tölt a szellemvilágban, ellenben Korra szabadon jár-kel, mégsem képes erre. Korra a szemére veti, hogy a Föld Királynőjének megölésével Zaheer utat nyitott egy még kegyetlenebb zsarnoknak, ami elgondolkoztatja Zaheert. Felajánlja Korrának, hogy segít neki átjutni a szellemvilágba, de ehhez lélekben túl kell tennie magát a múlton: a mérgezésen, a küzdelmen, azon, hogy majdnem meghalt. Zaheer vezetésével az Avatar végre megszabadul a kínzó emlékektől, jobban mondva képes feldolgozni a történteket, utána pedig megmenti a bajba került Jinorát és a turistákat.

        Bolin azon igyekszik, hogy visszaszerezze Opal bizalmát, de a lány árulónak tekinti őt. Végül Opal meggondolja magát, és felajánlja Bolinnak, hogy egy titkos küldetéssel talán tisztára moshatja magát. Lin és Opal ugyanis elhatározták, hogy kiszabadítják a családtagjaikat Kuvira fogságából. Bolin persze rögtön igent mond. Hirtelen becsatlakozik hozzájuk Toph is, aki az indák révén mindenről tudomást szerez, ami a világban történik. Kiszimatolják, hogy Kuvira tesztelni akarja az elkészült fegyvert, és ezt az alkalmat használják fel a rajtaütésre. Kiszabadítják Suyint, a férjét meg a két ikerfiút, de Bolin Zhu Lit is ki akarja menteni, mert Kuvira rájött a szabotázsára és fogságba vetette. Őt is kimenekítik, a Beifongok pedig túlteszik magukat a régi ellentéteken.

        Zhu Li megemlíti, hogy kihallgatta Kuviráékat, akik két hét múlva meg akarják támadni az Egyesült Köztársaságot. Raiko elnök parancsot ad a haderőnek a készültségre, és elrendeli a lakosság kimenekítését. Korra segítséget kér a szellemektől, de ők elutasítják, mondván, az emberek a szellemekkel a saját háborújukat akarják megvívni. Az Avatar Csapat figyeli a Föld Birodalmának seregét, Asami és Varrick pedig mecha tankokat gyártanak a köztársaság számára. A vezetők úgy gondolják, hogy a szellemindafegyvert vasúton fogják mozgatni, ezért lezárnak minden vasútvonalat, de hiába: Kuvira egy óriási robotot építtetett, annak karjára szerelték fel az ágyút. Ráadásul egy héttel korábban érkezik Köztársaságváros határába. A város alá érve felszólítja Raiko elnököt a megadásra, és ennek érdekében kicsit demonstrálja a fegyver erejét a hadiflottán. Raiko ennek hatására leteszi a fegyvert. Kuvira Baatart küldi az elnökhöz, hogy amaz megadja magát, de Korra és néhány levegőidomár elrabolja őt a léghajójáról, hogy kiszedjék belőle, hogyan lehet megállítani az óriási robotot. Rádiókapcsolat létesül Kuvira és az Avatar között, így derül fény a csínyre. Korra úgy veszi rá Baatart az együttműködésre, hogy megfenyegeti őt, mindenhová magával hurcolja túszként és soha többé nem láthatja Kuvirát. Baatarra ez hat végül, és beadja a derekát. Hajlandó segíteni és kérleli a jegyesét, hogy vonuljanak vissza. Ám Kuvira nem hajlandó meghátrálni, és kiderül, hogy a dicsőség még a szerelemnél is fontosabb számára, mert a szuperfegyverrel rálő az épületre, ahol Baatart tartják. Nagy nehezen megússzák a bent tartózkodók, Baatar pedig Kuvira árulása miatt végleg megbánja eddigi magatartását és anyjával is kibékül, segít az Avatar Csapatnak.

        A mecha tankok java része megsemmisül egy sugártól, amit az óriás robot lőtt ki, de maradt még néhány repülő robot, amelyekre plazma pengéket szerelnek. Mindez Hiroshi Sato ötlete, akit Lin Beifong kihoz a börtönből, mivel a szorult helyzetben minden intelligens elmére szükség van. Korra és társai megpróbálják feltartani az óriást, ezalatt Satóék a plazmavágókkal megpróbálnak lyukat vágni az óriásrobot platina testén. Forró a helyzet, és Hiroshi ekkor nehéz döntést hoz: lányát katapulttal kiveti a repülő robotból, ő viszont bent marad, amikor az óriás odacsap a kezével. Ezzel végleg jóvátett minden rosszat, amit Asami ellen elkövetett az egyenlőségiekkel való kacérkodása során. Asami rettentő szomorú apja elvesztése miatt, akinek végül teljesen megbocsátott. Mindenesetre a merész próbálkozás sikerült, Korráék bejutnak a robot testébe. Mako és Bolin kiiktatják az energiaforrást, Lin és Suyin pedig az ágyút semlegesítik, amely leszakad a robot testéről. Kuvira meglóg a robotból, Korra üldözőbe veszi. Viaskodnak egymással, Kuvira a robot leszakadt karjához fut, és bekapcsolja az ágyút. A sugárt azonban nem tudja megfékezni, leállítani, Korrának kell feltartóztatnia. A sugár akkora energiát szabadít fel, hogy egy új átjáró keletkezik a szellemvilágba. Oda kerül Korra és Kuvira is. Az utóbbi ellenáll és dühös, mert Korra az útjába állt. Igazolni akarja magát, hogy végig csak segíteni akart a Föld Népén. Korra megérti ezt, és végül együtt jönnek vissza az átjárón keresztül. A diktátor belátja vereségét, és parancsot ad a hadseregének a visszavonulásra, Lin és Suyin pedig foglyul ejtik őt.

        A befejezésben Varrick és Zhu Li házasságot kötnek, a lakodalmon Mako és Wu herceg beszélgetnek arról, hogy a herceg talán átvehetné a Föld Királyságának vezetését. De Wu kifejti megváltozott álláspontját, mely szerint a monarchia már elavult intézmény és inkább köztársaságot képzel el. Korra is helyesli az ötletet és segítséget ajánl Wunak. A keletkező szellemi átjáró körül megmarad a zöld terület. Asami is beszél Korrával, elmondja neki, hogy mennyire fáradtnak érzi magát az utóbbi idők eseményeitől, és szeretne pihenni, majd felveti, hogy már régóta szeretné megnézni a szellemvilágot. Korra jó ötletnek tartja és együtt lépnek be az új átjárón.
        <p>
                    </section>
</div>
<footer id="alsosav">
    <p class="oldal" >Korra Legendája</p>
    <a id="felgomb" href="#top">Vissza<br>az elejére</a>
</footer>
</body>
</html>